TABLE=$1
VAR_COLUMN=$2
OUTPUT_DIR=$3
SELECT_COLUMNS=${4:-"*"}

# if [ -z "$SUPERVISION_SAMPLE_QUERY_POS" ]; then # unset
#   psql -d $DBNAME -c "COPY (
#     SELECT $SELECT_COLUMNS
#     FROM $TABLE
#     WHERE $VAR_COLUMN = true
#     ORDER BY RANDOM() 
#     LIMIT $NUM_SAMPLED_SUPERVISION
#   ) TO STDOUT HEADER CSV;" > $OUTPUT_DIR/${TABLE}_true.csv;
# else # set
#   psql -d $DBNAME -c "COPY (
#     $SUPERVISION_SAMPLE_QUERY_POS
#     ORDER BY RANDOM() 
#     LIMIT $NUM_SAMPLED_SUPERVISION
#   ) TO STDOUT HEADER CSV;" > $OUTPUT_DIR/${TABLE}_true.csv;
# fi

# # TODO
# if [ -z "$SUPERVISION_SAMPLE_QUERY_NEG" ]; then
#   psql -d $DBNAME -c "COPY (
#     SELECT $SELECT_COLUMNS
#     FROM $TABLE
#     WHERE $VAR_COLUMN = false
#     ORDER BY RANDOM() 
#     LIMIT $NUM_SAMPLED_SUPERVISION
#   ) TO STDOUT HEADER CSV;" > $OUTPUT_DIR/${TABLE}_false.csv;
# else
#   psql -d $DBNAME -c "COPY (
#     $SUPERVISION_SAMPLE_QUERY_NEG
#     ORDER BY RANDOM() 
#     LIMIT $NUM_SAMPLED_SUPERVISION
#   ) TO STDOUT HEADER CSV;" > $OUTPUT_DIR/${TABLE}_false.csv;
# fi

psql -d $DBNAME -c "COPY (
  SELECT $SELECT_COLUMNS
  FROM $TABLE
  WHERE $VAR_COLUMN = true
  ORDER BY RANDOM() 
  LIMIT $NUM_SAMPLED_SUPERVISION
) TO STDOUT HEADER CSV;" > $OUTPUT_DIR/${TABLE}_true.csv

psql -d $DBNAME -c "COPY (
  SELECT $SELECT_COLUMNS
  FROM $TABLE
  WHERE $VAR_COLUMN = false
  ORDER BY RANDOM() 
  LIMIT $NUM_SAMPLED_SUPERVISION
) TO STDOUT HEADER CSV;" > $OUTPUT_DIR/${TABLE}_false.csv
