TABLE=$1
COLUMN=$2
OUTPUT_DIR=$3

psql -d $DBNAME -c "COPY (
  SELECT * 
  FROM $TABLE
  WHERE $COLUMN = true
  ORDER BY RANDOM() 
  LIMIT $NUM_SAMPLED_SUPERVISION
) TO STDOUT HEADER CSV;" > $OUTPUT_DIR/${TABLE}_true.csv

psql -d $DBNAME -c "COPY (
  SELECT * 
  FROM $TABLE
  WHERE $COLUMN = false
  ORDER BY RANDOM() 
  LIMIT $NUM_SAMPLED_SUPERVISION
) TO STDOUT HEADER CSV;" > $OUTPUT_DIR/${TABLE}_false.csv
