TABLE=$1
COLUMN=$2
OUTPUT_DIR=$3

psql -d $DBNAME -c " COPY (
  SELECT $COLUMN, count($COLUMN)
  FROM $TABLE
  GROUP BY $COLUMN
  ORDER BY count DESC
  LIMIT $NUM_SAMPLED_FEATURES
  ) TO STDOUT
" > $OUTPUT_DIR/$TABLE.tsv
